# Generated by Django 5.0.6 on 2024-05-30 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='demonstration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(default='https://example.com/default-video-url'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='fitness_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness_app.workout'),
            preserve_default=False,
        ),
    ]
